### PR TITLE
Add 1.16.1 Support

### PR DESCRIPTION
**Pull request by jackstrosahl**
I just changed copied 1.15 and changed to 1.16.  Seems to work.

### CODE REVIEW

**Comment by coelho** [comment]
Hi @jackstrosahl Can you confirm that you have tested and ensured that this is all working?

Thank you for your PR!

**Comment by jackstrosahl** [comment]
Do you have specifics I should test?  I've connected to the server and messed around a bit.

**Comment by coelho** [comment]
@jackstrosahl Just need to be sure that IPs & UUIDs in-game are correct.

**Comment by jackstrosahl** [comment]
Sorry, I'm not sure how to do that.  Through the CLI I can see my player's UUID is correct and they're connected from 127.0.01, is that adequate?

**Comment by coelho** [comment]
Sounds good to me.

**Pull request merged**
