### PR TITLE
Multi-version support with 1.9.4 and 1.10

### PR DESCRIPTION
**Pull request by Maescool**
Used #25 and added 1.9.4 and 1.10 support with that one

### CODE REVIEW

**Comment by coelho** [comment]
@Maescool Is it possible this fixes https://github.com/LilyPad/GoLilyPad/issues/35 ?

**Comment by Maescool** [comment]
@coelho Probably not.. However, will check it.

**Comment by Mast3rPlan** [comment]
This version does not support 1.7 and under because authlib is shaded in net.minecraft.util

**Comment by Maescool** [comment]
@coelho so, @Mast3rPlan 's changes also fix LilyPad/GoLilyPad#35 and probabbly other related UUID

**Comment by manuelgu** [comment]
Confirmed to be working

**Comment by fatboy2380** [comment]
I confirmed that it works, but the build I have skins are broken (approx 10 hours old)

**Comment by dordsor21** [comment]
@fatboy2380 just built latest version, testing it now.

**Comment by Maescool** [comment]
Skins were indeed broken, was fixed with 797b23a

**Comment by dordsor21** [comment]
seems to be working fine now (1.9.4 and 1.10)

**Comment by coelho** [comment]
1.8.8 works. Merging.

**Comment by AlfieC** [comment]
I had actually intended to rewrite my multi version PR as for some reason it can break on reload; but I'm not sure if that was standard LP behaviour or new behaviour my code had introduced. I can rewrite and create another PR if you'd like? Been a little bit busy as I'm sure you've all heard.

**Comment by coelho** [comment]
@AlfieC It's just normal LilyPad behavior that it doesn't work on reload haha. You can submit a PR if you want though to fix it, although it may make a mess of plugins that hook into LilyPad & ProtocolLib and all that stuff. I don't think it's a big deal.

**Comment by AlfieC** [comment]
@Coelho ah okay. Will investigate more and try to find a fix that doesn't make a mockery of ProtocolLib soon anyhow.

**Pull request merged**
